spring:
  profiles:
    active: local
    group:
      local:
        - common
        - oauth
        - jwt
      prod :
        - common
---
spring:
  config:
    activate:
      on-profile: common
    import: optional:file:.env[.properties]
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: DEBUG
        sql: DEBUG
  config:
    activate:
      on-profile: common

cloud:
  aws:
    credentials:
      accessKey: ${accessKey}
      secretKey: ${secretKey}
    region:
      static: ${region}
    stack:
      auto: ${stack_auto}
    s3:
      bucket: ${bucket}
  config:
    activate:
      on-profile: common
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/it
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssafy
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
